version: '3.8'

services:
  nodejs:
    build: .
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: sys
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
